# Generated by Django 5.1.1 on 2024-09-22 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_category_product_prdcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ALproduct_alternative', models.ManyToManyField(related_name='product_alternative', to='pages.product', verbose_name='product alternative')),
                ('ALproduct_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_name', to='pages.product', verbose_name='product name')),
            ],
        ),
    ]
