# Generated by Django 5.1.1 on 2024-09-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_product_alternative_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Bestsellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BSbestsellers', models.ManyToManyField(to='pages.product', verbose_name='best sellers')),
            ],
            options={
                'verbose_name': 'Best seller',
                'verbose_name_plural': 'Best seller',
            },
        ),
    ]
