# Generated by Django 5.1.1 on 2024-09-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_product_bestsellers'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Arrivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BSnewarrivals', models.ManyToManyField(to='pages.product', verbose_name='new arrivals')),
            ],
            options={
                'verbose_name': 'New arrival',
                'verbose_name_plural': 'New arrivals',
            },
        ),
    ]
