# Generated by Django 5.1.1 on 2024-09-23 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_product_bestsellers_options_product_hotsales'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDbrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.brand', verbose_name='product brand'),
        ),
    ]
