# Generated by Django 5.1.1 on 2024-09-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_product_prdbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDbase_productimage',
            field=models.ImageField(default=1, upload_to='products/%y/%m/%d', verbose_name='product image'),
            preserve_default=False,
        ),
    ]
