# Generated by Django 5.1.1 on 2024-09-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_product_prdbase_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDdiscountprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='product offer'),
        ),
    ]
