# Generated by Django 3.2.25 on 2024-10-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_product_prddiscountprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDdiscountprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=5, null=True, verbose_name='product offer'),
        ),
    ]
