# Generated by Django 3.2.25 on 2024-10-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_remove_product_prdbase_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDbase_productimage',
            field=models.ImageField(default=1, upload_to='products/%y/%m/%d', verbose_name='product image'),
            preserve_default=False,
        ),
    ]
