# Generated by Django 3.2.25 on 2024-10-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CONdescription', models.TextField(blank=True, max_length=200, null=True, verbose_name='description')),
                ('CONcountry1', models.CharField(blank=True, max_length=100, null=True, verbose_name='country 1')),
                ('CONaddress1', models.CharField(blank=True, max_length=100, null=True, verbose_name='address 1')),
                ('CONphone_number1', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number1')),
                ('CONcountry2', models.CharField(blank=True, max_length=100, null=True, verbose_name='country 2')),
                ('CONaddress2', models.CharField(blank=True, max_length=100, null=True, verbose_name='address 2')),
                ('CONphone_number2', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number2')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact US',
            },
        ),
    ]
