# Generated by Django 3.2.25 on 2024-10-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BLimage', models.ImageField(upload_to='blogs/%y/%m/%d', verbose_name='blog image')),
                ('BLdate', models.DateTimeField(verbose_name='date')),
                ('BLtitle', models.CharField(max_length=400, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
